name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DENO_DIR: ~/deps

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno: ["v1.30.1"]
        os: [ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions

      - name: Install dependencies
        run: deno task setup

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      - name: Run Tests
        run: deno task test

      - name: Run Linter
        run: deno task lint

      - name: Compile
        run: deno task build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/app
          retention-days: 3
      - name: Generate coverage.lcov
        run: deno task coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_SECRET}}
          file: ./coverage.lcov
          fail_ci_if_error: true
